spring:
  application:
    name: springai

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  ai:
    openai:
      api-key: test
      chat:
        options:
          model: gpt-4.0

    ollama:
      embedding:
        options:
          model: mxbai-embed-large
      chat:
        options:
          model: haybu/mistral-latest:latest

    vectorstore:
      pgvector:
        remove-existing-vector-store-table: true
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000
